### ISSUE TITLE
Bug collision detection

### ISSUE THREAD

**Issue by loia5tqd001** [dungdna2000/gamedev-intro-tutorials#1]
I tested project 4 and Mario-chan unfortunately went inside the brick.
To fix it, in _GameObject.cpp file, CGameObject::CalcPotentialCollisions_ function:
`if (e->t > 0 && e->t <= 1.0f)` would be `if (e->t >= 0 && e->t <= 1.0f)`. Because the case _e->t = 0_ means collision did occur, but with your test expression, it would not be recognized. Doing so, you also don't need to push Mario-chan out by _0.4f*ny_ (which caused blurry rendered) any more.

**Comment by dungdna2000** [comment]
Thanks. I'll take a look at this.

**Comment by dungdna2000** [comment]
Closed because this is not a valid error.
